<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAP9xxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAP9xxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQAP9xxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQAP9xxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQAP9xxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'QAP9xxv',
    'container.build_id' => 'd243ec40',
    'container.build_time' => 1592574901,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAP9xxv');
